development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: greenbean_development
  pool: 5
  username: postgres
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: greenbean_test
  pool: 5
  username: postgres 
  password: test

production:
  adapter: postgresql
  encoding: utf8
  database: greenbean_production
  pool: 5
  username: postgres
  password: test

cucumber:
  <<: *TEST