development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: greenbean_development
  pool: 5
  username: 
  password: 

  password: 
  
test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: greenbean_test
  pool: 5
<<<<<<< HEAD
  username:
=======
  username: 
>>>>>>> b1f8fe8a78998165432552f835747946e8b699c0
  password: 
    
production:
  adapter: postgresql
  encoding: utf8
  database: greenbean_production
  pool: 5
<<<<<<< HEAD
  username:
  password:
=======
  username: 
  password: 
>>>>>>> b1f8fe8a78998165432552f835747946e8b699c0

cucumber:
  <<: *TEST
  username:
  password:
