development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: greenbean_development
  pool: 5
  username: 
  password: 

  password: 
  
test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: greenbean_test
  pool: 5
  username: 
  password: 
    
production:
  adapter: postgresql
  encoding: utf8
  database: greenbean_production
  pool: 5
  username: 
  password: 

cucumber:
  <<: *TEST
  username:
  password:
